api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 5
    validator:
        serialize_payload_fields: ['code']
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        jsonhal:
            mime_types:
                - application/hal+json
        jsonapi:
            mime_types:
                - application/vnd.api+json
        json:
            mime_types:
                - application/json
