version: '3'
services:
    vuejs_rouzig:
        build:
            context: ./vuejs
            dockerfile: Dockerfile
            args:
                - YOUR_APP_WEB_HTTP_PORT=8080
        container_name: vuejs_rouzig
        ports:
            - "80:8080"
            - "8000:8000"  # only needed if using vue-cli UI
        volumes:
            - ../front:/www
        stdin_open: true
        tty: true
        environment:
            # https://cli.vuejs.org/guide/mode-and-env.html#modes
            # development is used by vue-cli-service serve
            - NODE_ENV=development
            # one way for hot reloading ... see above for details
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=100
            - YOUR_APP_WEB_HTTP_PORT=8080
