api_platform:
    formats:
        html:
            mime_types:
                - text/html
        jsonld:
            mime_types:
                - application/ld+json
        jsonhal:
            mime_types:
                - application/hal+json
