- name: Build package
  hosts: 127.0.0.1
  connection: local
  vars_prompt:
    - name: "version"
      prompt: "what is the version? (default: master)"
      default: master
  tasks:
    - name : check out git repo
      git: repo=git@github.com:lerouxguillaume/perso.git dest=/tmp/delivery_perso
    - name: composer install symfony
      command: chdir=/tmp/delivery_perso git checkout {{ version }}
    - name: npm install vue
      command: chdir=/tmp/delivery_perso/front npm install
    - name: npm build vue
      command: chdir=/tmp/delivery_perso/front npm run build
    - name: tar front end
      command: chdir=/tmp/delivery_perso/front/dist tar -hpcvzf /tmp/front.tar.gz --exclude='.svn' --exclude='.git' --exclude='.env' .
    - name: clean
      command: chdir=/tmp rm -rf delivery_perso

- name: Livraison
  hosts: prod
  tasks:
  - name: Copy front tar on prod serveur
    copy:
      src: /tmp/front.tar.gz
      dest: /var/www/front/sources/front.tar.gz
  - name: untar front
    command: chdir=/var/www/front/sources tar xzvf front.tar.gz -C ../services